version : "3.8"
services :
  stocks-app :
    build :
      context : .
      dockerfile : Dockerfile
    ports :
      - "8080:8080"
    depends_on :
      - zookeeper_stocks_app
      - broker_stocks_app
    environment :
      KAFKA_BOOTSTRAP_SERVERS : broker_stocks_app:9092
  zookeeper_stocks_app :
    image : confluentinc/cp-zookeeper:7.0.1
    container_name : zookeeper_stocks_app
    environment :
      ZOOKEEPER_CLIENT_PORT : 2181
      ZOOKEEPER_TICK_TIME : 2000
  broker_stocks_app :
    image : confluentinc/cp-kafka:7.0.1
    container_name : broker_stocks_app
    ports :
      - "9092:9092"
      - "9093:9093"
    depends_on :
      - zookeeper_stocks_app
    environment :
      KAFKA_BROKER_ID : 1
      KAFKA_ZOOKEEPER_CONNECT : 'zookeeper_stocks_app:2181'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR : 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR : 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR : 1
      KAFKA_LISTENERS : PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_C://0.0.0.0:9093,PLAINTEXT_L://0.0.0.0:9092,
      KAFKA_ADVERTISED_LISTENERS : PLAINTEXT_INTERNAL://broker_stocks_app:29092,PLAINTEXT_L://broker_stocks_app:9092,PLAINTEXT_C://broker_stocks_app:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP : PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_L:PLAINTEXT,PLAINTEXT_C:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME : PLAINTEXT_INTERNAL
